name: tensorflow_12_gpu_gym
dependencies:
  - python>=3.5
  - matplotlib
  - nomkl
  - numpy
  - pip
  - menpo::opencv3==3.1.0
  - asmeurer::pango # Because of undefined symbol error - see https://github.com/ContinuumIO/anaconda-issues/issues/368
  - pip:
    - "gym[all]"
    - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0rc0-cp35-cp35m-linux_x86_64.whl
